### PR TITLE
Add first post about Homebrew Website Club

### PR DESCRIPTION
**Pull request by mroderick**

### CODE REVIEW

**Comment by scottbert** [comment]
Looking good. AKQA has a space and they might be up for letting us use it if I ask nicely/get some of them involved? Failing that, maybe one of the co-working spaces will help out?

**Comment by mroderick** [comment]
> Looking good. AKQA has a space and they might be up for letting us use it if I ask nicely/get some of them involved?

Do you think they would let us use it on a regular basis?

**Comment by scottbert** [comment]
> > Looking good. AKQA has a space and they might be up for letting us use it if I ask nicely/get some of them involved?
> 
> Do you think they would let us use it on a regular basis?

They’ve done it for other regular groups (like once a month), however, all of those groups had someone actually in AKQA present (probably for insurance reasons) and I believe those people were usually organising the meets - I can try and find out more?

**Comment by mroderick** [comment]
> all of those groups had someone actually in AKQA present (probably for insurance reasons)

Yeah, that's kind of a challenge when we're not employed by local entities.

Perhaps Arpad/Moe can help out with unlocking Zalando :)
I can also reach out to someone I know in Zalando

**Comment by mroderick** [comment]
> I can try and find out more?

Please do!

**Comment by scottbert** [comment]
We should also ask The Twitters™

**Comment by mroderick** [comment]
Let's ask on Twitter, once the post is up

**Comment by mroderick** [comment]
I've reached out to my contact in Zalando

**Comment by mroderick** [comment]
I don't think this will get more comments, so I am merging it

**Pull request merged**
